---
title: "R Notebook"
output: html_notebook
---

```{r}
# library(BiocManager)
# BiocManager::install("DESeq2")
library(dplyr)
library(readr)
library(DESeq2)
```

```{r}
gene_data <- read_csv('Breast_GSE45827.csv')
head(gene_data)
```

```{r}
binary_class_data <- gene_data %>% 
  mutate(type = case_when(
    type == 'normal' ~ 'healthy',
    TRUE ~ 'cancer'
    )
  )

binary_class_data
```

```{r}
binary_class_data <- as.data.frame(t(binary_class_data))
head(binary_class_data)
```

```{r}
colnames(binary_class_data) <- binary_class_data[1,]
coldata <- as.data.frame(t(binary_class_data[c(2),]))
binary_class_data <- binary_class_data[-c(1,2),]

binary_class_data
coldata
```

```{r}
converted_binary <- type.convert(binary_class_data)
converted_binary
```

```{r}
has.neg <- apply(converted_binary, 1, function(row) any(row < 0))
which(has.neg)
```

```{r}
dds <- DESeqDataSetFromMatrix(countData = converted_binary,
                              colData = coldata,
                              design = ~ type)
dds
```

```{r}
library(affy)
gene_raw_data <- ReadAffy(celfile.path = "/Users/alex/Documents/GitHub/Breast-Cancer-Gene-Regulatory-Network-and-Risk-Prediction/Data/GSE45827_RAW/")
```

```{r}
assay_data <- assayData(gene_raw_data)$exprs
pheno_data <- phenoData(gene_raw_data)
feature_data <- featureData(gene_raw_data)
```

```{r}
arraysRMA = rma(gene_raw_data, normalize = FALSE)
```

```{r}
log_arraysRMAtable=exprs(arraysRMA)
count_table = as.data.frame(round(2^log_arraysRMAtable))
head(count_table)
```

```{r}
colnames(count_table) <- substr(colnames(count_table),8,10)
head(count_table)
```

```{r}
count_table <- count_table[-c(3,6,8,10,13,16,19,24,28,31,34,36,42,48,50,52,54,57,62,71,76,82,90)]
count_table
```

```{r}
colnames(count_table) <- as.integer(colnames(count_table))
count_table
```

```{r}
coldata <- as.data.frame(as.integer(colnames(count_table)))

colnames(coldata) <- 'Sample'

coldata <- coldata %>% 
  mutate(type = case_when(
    Sample > 168 & Sample < 180 ~ 'non-cancer',
    TRUE ~ 'cancer'
    )
  )

coldata
```

```{r}
dds <- DESeqDataSetFromMatrix(countData = count_table,
                              colData = coldata,
                              design = ~ type)
dds
```

```{r}
# Pre-filtering
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]
```

```{r}
dds$type <- relevel(dds$type, ref = "non-cancer")
```

```{r}
dds <- DESeq(dds)
res <- results(dds)
res
```

```{r}
resultsNames(dds)
```

```{r}
# Log Fold Change Shrink
resLFC <- lfcShrink(dds, coef="type_cancer_vs_non.cancer", type="apeglm")
resLFC
```

```{r}
resOrdered <- res[order(res$pvalue),]
resOrdered
```

```{r}
GDE = data.frame(resOrdered$log2FoldChange, resOrdered$pvalue)
rownames(GDE) = resOrdered@rownames
colnames(GDE) = c('Log2FoldChange','Ordered$pvalue')
GDE
```

```{r}
write.csv(GDE, "GDE_Outcome.csv", row.names = TRUE)
```


